service:
  port: 8080
  host: http://localhost
  accept_expired: true
  accept_no_expire: true

database:
  driver: mysql
  conn: test:test@tcp(host.docker.internal:3306)/test?charset=utf8mb4&parseTime=True&loc=Local

redis:
  conn: host.docker.internal:6379